### ISSUE TITLE
Add Logging support

### ISSUE THREAD

**Issue by alorma** [vestrel00/contacts-android#144]
Right now the library depends on android `Log` feature, but it cannot be customized nor hide, causing potential leaks on some apps.

Are you open to a PR that adds a `Logger` on same way many apps do?

On this case, my idea is to create a `Logger` interface, and default implementation that relies on android `Log`, but allows to create another one, so for example Timber

**Comment by vestrel00** [comment]
I'm open to this! As long as you don't add new dependencies to this project, I think it would be cool! I'm trying to keep the library dependencies to a minimum.

I like your idea of using android Log as the default implementation of this library. 

It would be great if you could file a PR with partial implementation of what you have in mind. We can then talk about the internal architecture, consumer usage, and what should be logged and when. Then, when we come to an agreement, you can proceed to implement the whole thing 😁 🔥 

I'm excited to have you propose this and possibly own this part of this library!!!

**Comment by alorma** [comment]
Added on #145

**Comment by vestrel00** [comment]
Included in release; https://github.com/vestrel00/contacts-android/releases/tag/0.1.10
