### ISSUE TITLE
Shorten usage of Fields in include, where, and orderBy API functions

### ISSUE THREAD

**Issue by vestrel00** [vestrel00/contacts-android#150]
### Problem

The suggested usage of `Fields` in the library results in too long statements due to redundancy of using `Fields.`. For example,

```kotlin
.where((Fields.Email.Address startsWith "a") and (Fields.Email.Address endsWith "gmail.com"))
```

While this is the only way `Fields` can be used by Java users, we can shorten it for Kotlin users. Actually, Kotlin users can already remove the redundant calls to `Fields.` this by using `run` on it,

```kotlin
.where(Fields.run { (Email.Address startsWith "a") and (Email.Address endsWith "gmail.com") })
```

However, it is not obvious and requires consumers to still use `Fields.` once.

Consumers could also import all properties of `Fields`. However, it could cause a lot of name clashes between the name of the field (e.g. Email) and the name of the entity (e.g. Email).

### Solution

Remove the need for consumers to use `Fields.run` (and other equivalent field sets), in  `include`, `where`, and `orderBy` API functions.

Usage for Kotlin users would look like,

```kotlin
.where{ (Email.Address startsWith "a") and (Email.Address endsWith "gmail.com") }
```

This also gets rid of the need for consumers to know that they should be using `Fields` to begin with, even though it is mentioned in the documentation.

We can take this a step further by providing extensions for a field sets,

```kotlin
.where{ Email { (Address startsWith "a") and (Address endsWith "gmail.com") } }
```

And even further by providing extensions for individual fields,

```kotlin
.where{ Email.Address { startsWith("a") and endsWith("gmail.com") } }
```

### Checklist

- [x] Add the extra functions to all APIs
- [x] Update sample Kotlin code in API class docs
- [x] Update all relevant howto pages
- [x] Update README
- [x] Update medium and dev.to blog code snippets
- [x] Update sample app usages

**Comment by JayaSuryaT** [comment]
Hi @vestrel00,
(Continuing conversation from [here](https://www.reddit.com/r/Kotlin/comments/rtxfdm/creating_a_typesafe_where_clause_dsl_using_kotlin/hqyhumw/))

Would this thread be appropriate to continue the above mentioned conversation?

**Comment by vestrel00** [comment]
Hey! Welcome 🔥 Anywhere is fine. This is okay. If you'd like, you can start a new discussion https://github.com/vestrel00/contacts-android/discussions/new it's all up to you. I have no preference 😁 

> For my reference and other contributors, this is about this thread in Reddit; https://www.reddit.com/r/Kotlin/comments/rtxfdm/creating_a_typesafe_where_clause_dsl_using_kotlin/hr1jwk6/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3

**Comment by JayaSuryaT** [comment]
Stated a new discussion ([#162](https://github.com/vestrel00/contacts-android/discussions/162)) to continue on this.

**Comment by vestrel00** [comment]
Based on that discussion, I'm reopening this issue and assigning it to you @JayaSuryaT! Please delete my 500 lines of code here and replaced it with your 2 lines of code!!! GENIUS!

**Comment by vestrel00** [comment]
Included in release; https://github.com/vestrel00/contacts-android/releases/tag/0.1.10
