### ISSUE TITLE
Remove Account restrictions for Group, GroupMembership, Relation, and Event

### ISSUE THREAD

**Issue by vestrel00** [vestrel00/contacts-android#167]
Currently, the library has artificially placed some "Account restrictions" on certain entities. 

- Insert and update operations for these data kinds of a local RawContact (not associated with an Account) are not allowed (ignored); `GroupMembership`, `Relation`, and `Event`. 
- Query, Insert, and update operations for `Group` entities require an `android.accounts.Account`. 

The library imposes these restrictions because the native/default Contacts app does the same as described in my documentation;

<img width="834" alt="Screen Shot 2022-01-07 at 6 29 02 PM" src="https://user-images.githubusercontent.com/4332753/148631557-825dfb47-7e1d-4fb8-a0c8-1e45a4abdcb9.png">

## Problem

I recently started playing around with the [Google Contacts app](https://play.google.com/store/apps/details?id=com.google.android.contacts&hl=en_IN&gl=US). So... it turns out that the [Google Contacts app](https://play.google.com/store/apps/details?id=com.google.android.contacts&hl=en_IN&gl=US) DOES NOT impose these Account restrictions whereas the default Android Open Source Project (AOSP) Contacts app does.

| AOSP Contacts app                                                                                                                                                       | Google Contacts app                                                                                                                                                     |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="300" alt="Screen Shot 2022-01-07 at 6 49 23 PM" src="https://user-images.githubusercontent.com/4332753/148631925-a2b68e3e-246f-46cc-81c6-a943c9d3c689.png"> | <img width="308" alt="Screen Shot 2022-01-07 at 6 49 00 PM" src="https://user-images.githubusercontent.com/4332753/148631927-e3000b72-5a93-4769-80c8-34c6a4bc5c33.png"> |

**The Contacts Provider AND Google Contacts app does not impose these Account restrictions** whereas the AOSP Contacts app does.

## Solution

**Remove these Account restrictions**! Let the users of the library determine what to do instead of imposing these artificial restrictions on them!

- [x] `GroupEntity.account` should be nullable.
- [x] Allow query, insert, and update operations for `Group`s that have a null Account ("local groups").
- [x] Allow insert and update operations for `GroupMembership` data kinds belonging to local RawContacts.
- [x] Allow insert and update operations for `Event` data kinds belonging to local RawContacts.
- [x] Allow insert and update operations for `Relation` data kinds belonging to local RawContacts.

## Other things to do

- [x] Update sample app. Do not hide these fields in the UI anymore!
- [x] Test behavior in a non-Samsung phone (a pixel device/emulator).
- [x] Test behavior in a Samsung phone where the "local account" is not null but rather `vnd.sec.contact.phone`.
- [x] Update all in-code documentation. Go through all of `grep --include="*kt" -ri "account" .`
- [x] Update docs. Go through all of `grep --include="*md" -ri "account" .`
- [x] Update dev-notes.
- [x] Update README.
- [x] Provide a **migration guide** as a comment in this issue so that it can be copy-pasted into the release notes. 
- [x] Start working on #73 after this.

**Comment by CODES77** [comment]
CODES77

**Comment by vestrel00** [comment]
## Migration guide (to be included in release notes)

**[PREVIOUSLY](https://github.com/vestrel00/contacts-android/blob/0.2.4/docs/entities/about-local-contacts.md#data-kinds-account-restrictions)**, the following data kinds were ignored during insert and update operations for local RawContacts (those that are not associated with an Account);

- `GroupMembership`
- `Event`
- `Relation`

This meant that the insert and update APIs would not let you set the values of the above data kinds for local RawContacts... You might have noticed this and thought it was a bug. However, it was intentional 😅 

Another artificially imposed "restriction" that existed was that `GroupEntity.account` was NOT nullable. This meant that the library did not allow you to insert new groups that were not associated with an account. You were also not able to use the `GroupsQuery` API to fetch only groups that had no account (local groups). Furthermore, groups that were fetched that did have a null account in the database table were assigned a non-null account with the value `Account("null", "null)` (that is bad).

**NOW**, 

- the aforementioned data kinds are no longer ignored during insert and update operations for local RawContacts
- `GroupEntity.account` is nullable, allowing you to insert local groups 
- `GroupsQuery` API now supports fetching only local groups
- Groups that have a null account in the database table are properly assigned a null account value

Read the new documentation at; https://vestrel00.github.io/contacts-android/entities/about-local-contacts/#data-kinds-account-restrictions

**Comment by vestrel00** [comment]
This is included in [0.3.0](https://github.com/vestrel00/contacts-android/releases/tag/0.3.0)!
