### ISSUE TITLE
Convert the default Phone app to default dialer

### ISSUE THREAD

**Issue by Gliting29** [vestrel00/contacts-android#295]
I have converted my application to default dialer using this package using the code below:

```kotlin
import contacts.ui.util.requestToBeTheDefaultDialerApp

requestToBeTheDefaultDialerApp()
```

I want a function to convert back the default Phone app in mobile as default dialer. Is there any possibility to do so? It would be a great help.

**Comment by vestrel00** [comment]
I will close this issue for now. More context in https://github.com/vestrel00/contacts-android/discussions/294#discussioncomment-6694087
