### ISSUE TITLE
Why do deleted contacts from SIM card in Huawei device comes back after device restart?

### ISSUE THREAD

**Issue by wumeixinjiazu** [vestrel00/contacts-android#347]
On Huawei devices, when using Sample to delete contacts of SIM cards, the contact list is successfully viewed. However, after the device is restarted, the deleted contacts are recovered, including the modification of contacts.

Device info: HUAWEI BKL-L09 Android 9

**Comment by vestrel00** [comment]
Hey! Can you try deleting SIM card contacts using other applications? Then, restart the device and see if the deleted contacts are recovered.

I want to know if this is a bug with this library or it's the Huawei device.

**Comment by wumeixinjiazu** [comment]
> Hey! Can you try deleting SIM card contacts using other applications? Then, restart the device and see if the deleted contacts are recovered.
> 
> I want to know if this is a bug with this library or it's the Huawei device doing something to restore the SIM card into a previous state after restarting.

Yes, I have used your sample on Samsung's mobile phone, and there is no such problem. The code has been modified or the backup has been made in the Huawei system.

**Comment by vestrel00** [comment]
Thanks for verifying! It seems like the "issue" is with the Huawei device and not this library.

I will close this issue.
