### ISSUE TITLE
Sample app: create, update, and delete group

### ISSUE THREAD

**Issue by vestrel00** [vestrel00/contacts-android#73]
Wait for #167 before working on this.

- [x] Create group
- [x] Update group
- [x] Delete group
- [x] Test behavior in a non-Samsung phone (a pixel device/emulator).
- [ ]  Test behavior in a Samsung phone where the "local account" is not null but rather `vnd.sec.contact.phone`.

**Comment by CODES77** [comment]
CODES77

**Comment by CODES77** [comment]
CODES77
