### ISSUE TITLE
Sample app: settings - import contacts from SIM

### ISSUE THREAD

**Issue by vestrel00** [vestrel00/contacts-android#81]
Requires #25 and #212.

**Comment by vestrel00** [comment]
I did some testing on how the Google Contacts app implements import from SIM function. Here are the rules;

1. Contacts in the SIM card that have a matching name (case sensitive) in the Contacts Provider database will NOT be imported.
2. Contacts in the SIM card that have no name (null) but have a matching number (matching the number exactly with formatting characters included- ignores the normalized number) in the Contacts Provider database will NOT be imported.

I will follow the same rules!

**Comment by CODES77** [comment]
> Requires #25 and #212.

CODES77
